### ISSUE TITLE
Using AsyncContext for globals?

### ISSUE THREAD

**Issue by slorber** [tc39/proposal-async-context#84]
It's a crazy idea. I'm not sure this discussion belongs to this repo, but this feels related so I'm giving it a try.

## Fact: people patch globals

Over the years, countless people have patched/extended globals of their JS runtime.

More recently, [React and Next.js patching `fetch()` in Server Components environment to add caching](https://twitter.com/rickhanlonii/status/1783486563755643181) let to controversy and the feature has been removed.

## Proposed idea: use AsyncContext for globals

What if we could do local dependency injection of globals? 

What if we could enable libs/frameworks to alter globals safely for a whole execution flow, that is convenient, and yet does not need to modify the underlying runtime?

What if we could improve the testability of apps using globals at the same time, as an alternative to solutions such as [Mock Service Worker](https://mswjs.io/)?

## Example implementation

This is just pseudo code but I think this kind of API could be interesting to have:

```tsx
// This uses runtime global fetch
const result = await fetch("/user");

AsyncContext.Globals.run(
  // Provides custom fetch for the underlying execution flow
  { fetch: myCustomFetch },
  async () => {
    // This uses the custom fetch
    const result = await fetch("/user");

    AsyncContext.Globals.run(
      // Reverts the custom fetch for the underlying execution flow
      { fetch: null },
      async () => {
        // This uses runtime global fetch
        const result = await fetch("/user");
      },
    );
  },
);
```

**Comment by legendecas** [comment]
Thanks for sharing! This is an interesting use case. I believe this could be built in userland based on the necessary capability AsyncContext provides. Also, I'd find that this would be a use case that doesn't expect the values to be changed around `await` calls, mentioned in https://github.com/tc39/proposal-async-context/issues/83.

I'm closing this since this is an extension could be done in userland. Please feel free to re-open if you find it is not the case.
